### ISSUE TITLE
Usability thoughts regarding extension

### ISSUE THREAD

**Issue by neubig** [zaidsheikh/cmulab_elan_extension#1]
* [ ] There is a link to the cmulab repository in the README, but the cmulab repository is private. It could potentially be made public.
* [x] The parameters menu is quite small vertically and a bit hard to navigate:

![Screen Shot 2022-04-13 at 1 27 56 PM](https://user-images.githubusercontent.com/398875/163236846-c76353f5-6670-4951-b135-f0873c69cc56.png)

* [ ] It'd probably be good to have some minimal documentation of each capability that the ELAN plugin provides (diarization, phone recognition, training). It could be added to a separate `.md` perhaps.
* [x] For diarization, the output is still labeled something like "output recognized text". Maybe it should be "output tier name" or something to make this more general.
* [x] The "authorization required" screen was black for me (on mac)

<img width="338" alt="Screen Shot 2022-04-13 at 1 34 16 PM" src="https://user-images.githubusercontent.com/398875/163238022-ddddef7b-378a-40bf-8604-b1c6519412d5.png">

**Comment by zaidsheikh** [comment]
Unfortunately the default size of the parameters section is set by ELAN, there's no way to change it via the plugin. I have added instructions at the end of the README.md on how to re-size the parameters section or pop it out in a new window.

I added some documentation for each of the services [here](https://github.com/zaidsheikh/cmulab_elan_extension/blob/main/cmulab_services.md). This page can also be viewed directly from inside the ELAN plugin by clicking this button ![image](https://user-images.githubusercontent.com/2358298/164254516-2e97f7b5-842f-4e30-a84f-3ad09a9263d9.png) located below the parameters section.

>  For diarization, the output is still labeled something like "output recognized text". Maybe it should be "output tier name" or something to make this more general.

Changed the label to "Output tier"

> The "authorization required" screen was black for me (on mac)

The built-in Tk GUI library in Apple-supplied Python 3 in some macOS versions (such as macOS 12 Monterey) have bugs that cause dialog boxes to not display properly. The easiest way to fix this is to install the latest python from [python.org](https://www.python.org/downloads/). However I have also released a pyinstaller distribution for macOS that bundles a working version of python here:
https://github.com/zaidsheikh/cmulab_elan_extension/releases/tag/v0.0.1
Added a note in the README in case other users encounter the same issue.
